[package]
name = "playground"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
graphiti = { path = ".." }
leptos = { version = "0.7", features = ["csr"] }
js-sys = "0.3"
wasm-bindgen = "=0.2.115"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = [
    "CanvasRenderingContext2d",
    "Document",
    "Element",
    "Event",
    "EventTarget",
    "HtmlAnchorElement",
    "HtmlCanvasElement",
    "HtmlElement",
    "HtmlImageElement",
    "HtmlPreElement",
    "HtmlSelectElement",
    "HtmlTextAreaElement",
    "Node",
    "Window",
] }
